trigger:
  branches:
    include:
      - main

pool:
  vmImage: rohith

steps:
- task: AzureCLI@2
  displayName: 'Install kubectl'
  inputs:
    azureSubscription: 'new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install kubectl
      az aks install-cli

- task: AzureCLI@2
  displayName: 'Get AKS Credentials'
  inputs:
    azureSubscription: 'new'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get AKS credentials
      az aks get-credentials --resource-group new --name rohith

- task: AzureCLI@2
  displayName: 'Kubectl Get Pods'
  inputs:
    azureSubscription: 'new'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Run kubectl get pods command
      kubectl get pods

- task: AzureCLI@2
  displayName: 'Kubectl Logs Pod'
  inputs:
    azureSubscription: 'new'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Run kubectl logs command
      kubectl logs my-pod


