trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Install kubectl'
  inputs:
    azureSubscription: '56374a4e-7e63-4d89-8e8e-2e57019720c6'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install kubectl
      az aks install-cli



# Add more steps for your deployment process here
